cursor none
cursor_trail 1

disable_ligatures always

scrollback_lines 10000

enable_audio_bell no

hide_window_decorations yes
confirm_os_window_close 0

background_opacity 0.9
dynamic_background_opacity yes

background #1a1b26
foreground #c0caf5

selection_background #283457
selection_foreground #c0caf5

# black
color0 #16161e
color8 #565f89

# red
color1 #f7768e
color9 #f7768e

# green
color2 #9ece6a
color10 #9ece6a

# yellow
color3 #e0af68
color11 #e0af68

# blue
color4 #7aa2f7
color12 #7aa2f7

# magenta
color5 #bb9af7
color13 #bb9af7

# cyan
color6 #89ddff
color14 #89ddff

# white
color7 #a9b1d6
color15 #c0caf5
