cursor none

background #e1e2e7
foreground #3760bf

selection_background #b7c1e3
selection_foreground #3760bf

active_tab_background   #2e7de9
active_tab_foreground   #b4b5b9
inactive_tab_background #c4c8da
inactive_tab_foreground #8990b3
# tab_bar_background      #d0d5e3

active_border_color   #2e7de9
inactive_border_color #c4c8da

url_color #2e7de9

# black
color0  #b4b5b9
color8  #a1a6c5

# red
color1  #f52a65
color9  #ff4774

# green
color2  #587539
color10 #5c8524

# yellow
color3  #8c6c3e
color11 #a27629

# blue
color4  #2e7de9
color12 #358aff

# magenta
color5  #9854f1
color13 #a463ff

# cyan
color6  #007197
color14 #007ea8

# white
color7  #6172b0
color15 #3760bf

# extended colors
color16 #b15c00
color17 #c64343
