[bar.default]
background_opacity = 0.9
capsule = true
capsule_padding = 4.0
capsule_radius = 8
center = [ "group:g1", "group:g2" ]
end = [
    "tray",
    "keyboard_layout",
    "clipboard",
    "network",
    "bluetooth",
    "output_volume",
    "input_volume",
    "brightness",
    "battery",
    "notifications",
    "control-center"
]
margin_ends = 0
padding = 8
position = "left"
radius_bottom_left = 0
radius_top_left = 0
start = [ "launcher", "taskbar", "media" ]
thickness = 36
widget_spacing = 4

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "temp", "cpu", "ram" ]
    opacity = 1.0
    padding = 4.0
    radius = 8.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "clock", "date" ]
    opacity = 1.0
    padding = 4.0
    radius = 8.0

[battery]
warning_threshold = 20

[keybinds]
down = [ "Down", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+k" ]
validate = [ "Return", "KP_Enter", "space", "Ctrl+y" ]

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 213.0
    box_width = 810.0
    cx = 960.0
    cy = 889.5
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true
        show_session_buttons = true

[nightlight]
enabled = true

[shell.panel]
session_placement = "floating"
session_position = "center"

[shell.screenshot]
directory = "/home/saff/Pictures/Screenshots"

[theme]
builtin = "Tokyo-Night"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "qt" ]
    community_ids = [ "zen-browser" ]

[wallpaper]
transition_on_startup = true

    [wallpaper.automation]
    enabled = true
    recursive = false

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.control-center]
glyph = "adjustments"

[widget.cpu]
show_label = false

[widget.input_volume]
show_label = false

[widget.keyboard_layout]
show_icon = false

[widget.launcher]
custom_image = "/home/saff/Pictures/nix-snowflake-colours.svg"
scale = 1.5

[widget.network]
show_label = false

[widget.output_volume]
show_label = false

[widget.ram]
show_label = false

[widget.taskbar]
group_by_workspace = true
inactive_opacity = 0.8

[widget.temp]
show_label = false

[widget.tray]
drawer = true

[widget.volume]
show_label = false
