[mgr]
cwd = { fg = 'white' }
border_style = { fg = 'blue' }

[tabs]
active = { bg = 'blue', fg = 'black', bold = true }
inactive = { bg = 'black', fg = 'blue' }

[mode]
normal_main = { bg = 'blue', fg = 'black', bold = true }
normal_alt = { bg = 'lightgray', fg = 'black', bold = true }
select_main = { bg = 'red', fg = 'black', bold = true }
select_alt = { bg = 'lightgray', fg = 'black', bold = true }
unset_main = { bg = 'red', fg = 'black' , bold = true }
unset_alt = { bg = 'lightgray', fg = 'black', bold = true }

[status]
progress_normal = { bg = 'black', fg = 'green' }
progress_error = { bg = 'black', fg = 'red' }
